export const CREATE_NEW_QUESTION = 'CREATE_NEW_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const FETCH_QUESTION = 'FETCH_QUESTION';
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'; 
export const POST_NEW_QUESTION = 'POST_NEW_QUESTION';